RUN \ 
pushd /usr/lib/kernel/install.d && \ 
mv 05-rpmostree.install 05-rpmostree.install.bak && \ 
mv 50-dracut.install 50-dracut.install.bak && \ 
printf '%s\n' '#!/bin/sh' 'exit 0' > 05-rpmostree.install && \ 
printf '%s\n' '#!/bin/sh' 'exit 0' > 50-dracut.install && \
chmod +x 05-rpmostree.install 50-dracut.install && \
popd